// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200612155844_AddIdentity")]
    partial class AddIdentity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccessLayer.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EducationalDirection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BudgetPlacesCount")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EducationalDivisionId")
                        .HasColumnType("int");

                    b.Property<int>("EducationalForm")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaidPlacesCount")
                        .HasColumnType("int");

                    b.Property<double>("PeriodOfStudy")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EducationalDivisionId");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EducationalDivision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            ModifiedDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            Name = "Физика"
                        },
                        new
                        {
                            Id = 2,
                            CreateDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            ModifiedDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            Name = "Химия"
                        },
                        new
                        {
                            Id = 3,
                            CreateDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            ModifiedDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            Name = "Русский язык"
                        },
                        new
                        {
                            Id = 4,
                            CreateDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            ModifiedDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            Name = "Математика(профильная)"
                        },
                        new
                        {
                            Id = 5,
                            CreateDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            ModifiedDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            Name = "Биология"
                        },
                        new
                        {
                            Id = 6,
                            CreateDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            ModifiedDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            Name = "Творческий конкурс"
                        },
                        new
                        {
                            Id = 7,
                            CreateDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            ModifiedDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            Name = "Спортивная дисциплина"
                        },
                        new
                        {
                            Id = 8,
                            CreateDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            ModifiedDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            Name = "География"
                        },
                        new
                        {
                            Id = 9,
                            CreateDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            ModifiedDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            Name = "Обществознание"
                        },
                        new
                        {
                            Id = 10,
                            CreateDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            ModifiedDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            Name = "Литература"
                        },
                        new
                        {
                            Id = 11,
                            CreateDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            ModifiedDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            Name = "История"
                        },
                        new
                        {
                            Id = 12,
                            CreateDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            ModifiedDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            Name = "Информатика"
                        },
                        new
                        {
                            Id = 13,
                            CreateDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            ModifiedDateTime = new DateTime(2020, 6, 12, 18, 58, 43, 676, DateTimeKind.Local).AddTicks(8078),
                            Name = "Иностранный язык"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.SubjectScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EducationalDirectionId")
                        .HasColumnType("int");

                    b.Property<int>("MinimumScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EducationalDirectionId");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectScores");
                });

            modelBuilder.Entity("DataAccessLayer.Models.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePathInDirectory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Page")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EducationalDirection", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EducationalDivision", "EducationalDivision")
                        .WithMany("EducationalDirections")
                        .HasForeignKey("EducationalDivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.EducationalDivision", b =>
                {
                    b.HasOne("DataAccessLayer.Models.University", "University")
                        .WithMany("Divisions")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.SubjectScore", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EducationalDirection", "EducationalDirection")
                        .WithMany("SubjectScores")
                        .HasForeignKey("EducationalDirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Subject", "Subject")
                        .WithMany("SubjectScores")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
